### ISSUE TITLE
Issue with XML package in Github r-lib v2 actions

### ISSUE THREAD

**Issue by mpadge** [eblondel/atom4R#13]
The XML package is [considered obsolete](https://devguide.ropensci.org/building.html#recommended-scaffolding) and currently causing widespread build failures on GitHub actions, including R CMD Check on ubuntu, and test coverage which by default runs on the failing environment. That means that no packages which depend on {atom4R} can be tested on GitHub. It would be good for future-proofing to replace XML with xml2.

**Comment by eblondel** [comment]
No, i don't have intention to move from XML to xml2 right now. XML package is far from being considered obsolete by the R community and is maintained by CRAN team with many reverse dependencies which makes it still an essential piece of software for R packages; See https://cran.r-project.org/package=XML 
See https://github.com/eblondel/ows4R/issues/59 where same question was asked by @maelle and also this https://github.com/eblondel/ows4R/issues/71

**Comment by eblondel** [comment]
This is something, as you say, that should be done for future-proofing, and I had it in my mind already because most of packages I've authored are XML based. atom4R is quite new but when i've created all the others, xml2 was still at very early stage with no flexible encoding capacities, the reason why XML has been kept. As I said, although it is not maintained anymore by the original author (be careful with this repo https://github.com/omegahat/XML that is not maintained and not in sync with CRAN). The XML package as published in CRAN is not managed in Github, and maintained by CRAN team

**Comment by mpadge** [comment]
We at rOpenSci nevertheless base our recommendations and list of carefully curated best practices on years of experience. In this case that experience results in us stronly recommending that developers use xml2 rather than XML. Although the latter was eventually taken over by CRAN members, it is still not particularly actively maintained, is prone to the kinds of breakages that currently make {atom4R} uninstallable on any current ubuntu systems, and has no way of reporting bugs like these.

To make this discussion more concrete: We have comprehensive statistics from the entire CRAN archive which also show the average incremental effects of package updates (as percentages):

package | increase in code lines | increase in doc lines
--- | --- | ---
xml2 | 0.53 | 0.92
XML | -0.02 | 0.04

By those simple measures, xml2 is orders of magnitude better maintained that XML.

That said, your reasons for XML here are indeed understandable, and I'm happy for you to close this for now if you don't intend to adapt just yet. We can always return later if problems persist. Thanks

**Comment by eblondel** [comment]
Being actively **maintained** doesn't mean that you have active **development**, XML is very exhaustive and stable, and when a package is exhaustive you don't need extra development and minimal maintenance to have it working. 

atom4R is installable in ubuntu systems, proof is the Github CI in place github.com/eblondel/atom4R/blob/master/.github/workflows/r-cmd-check.yml#L18 and I use it with partners on production Rstudio servers built on ubuntu. You may need to dig further in specific Github CI r dependency installation actions, as pointed out to @maelle in https://github.com/eblondel/ows4R/issues/71 on which i'm still investigating to help @maelle on her github actions. Having these specific Github action failures doesn't mean that it's not installable on ubuntu systems.

**Comment by eblondel** [comment]
I'm renaming this ticket since your initial issue is actually about the Github builds, and not really the switch to xml2
Similarly to https://github.com/eblondel/ows4R/issues/71 in support to @maelle for https://github.com/EMODnet/EMODnetWFS/ i've reinforced the Github CI R cmd check, by:
* upgrading to v2 actions,
* making sure to declare {XML} package as `extra-packages` not to use a cache old version of XML package and to install the latest from CRAN.
* test on both R `release` and `devel` on `ubuntu-latest`

With this I suppose you have a hint to fix your package github builds.

In reply to your strong 'statements' over {atom4R} and packages that rely on XML :
* https://github.com/eblondel/atom4R/issues/13#issue-1238649698 _"That means that no packages which depend on {atom4R} can be tested on GitHub."_: packages which depend on {atom4R} (or on any package that uses XML) can be tested on GitHub on the plateform of your choices, including Ubuntu
* https://github.com/eblondel/atom4R/issues/13#issuecomment-1129023509 _"kinds of breakages that currently make {atom4R} uninstallable on any current ubuntu systems"_ : atom4R is installable on ubuntu systems, the proof is in the atom4R Github CI action.
